name: Publish to AUR

on:
  release:
    type: [ published ]

jobs:
  publish_aur_package:
    if: github.event.base_ref == 'refs/heads/master'
    name: 'Publish to AUR'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download archive
        run: wget https://github.com/sidusio/boogrocha/archive/${GITHUB_REF##*/}.tar.gz

      - name: Update PKGBUILD
        run: |
          sed -i "s/tag=/tag=${GITHUB_REF##*/}/g" build/PKGBUILD
          sed -i "s/sha256sums=/sha256sums='$(sha256sums=$(sha256sum ${GITHUB_REF##*/}.tar.gz)'/g" build/PKGBUILD

      - name: Publish AUR package
        uses: KSXGitHub/github-actions-deploy-aur@v2.2.0
        with:
          pkgname: boogrocha
          pkgbuild: build/PKGBUILD
          commit_username: githubaction
          commit_email: boogrocha@sidus.io
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          force_push: true # optional, default is false
