name: Publish to AUR

on:
  push:
    tags:
      - 'v*.*.*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  publish_aur_package:
    if: github.event.base_ref == 'refs/heads/master'
    name: 'Publish to AUR'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Update PKGBUILD
        run: sed -i "s/TAG/${GITHUB_REF##*/}/g" build/PKGBUILD

      - name: Publish AUR package
        uses: KSXGitHub/github-actions-deploy-aur@v2.2.0
        with:
          pkgname: boogrocha
          pkgbuild: build/PKGBUILD
          commit_username: githubaction
          commit_email: boogrocha@sidus.io
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          force_push: true # optional, default is false

  create_github_release:
    name: 'Create Github release'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${GITHUB_REF##*/}
          release_name: Release ${GITHUB_REF##*/}
          draft: true
          prerelease: false
